// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Grid from "./Grid.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";

function App(props) {
  return JsxRuntime.jsx("div", {
              children: JsxRuntime.jsx(Grid.make, {}),
              className: "p-6"
            });
}

var make = App;

export {
  make ,
}
/* Grid Not a pure module */
