// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

function Placeholder(props) {
  return JsxRuntime.jsx("p", {
              children: "Press \"Begin Game\" to start!"
            });
}

var make = Placeholder;

export {
  make ,
}
/* react/jsx-runtime Not a pure module */
